AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  This template sets up CD pipeline for serverless-cognito-auth
Parameters:
  GitHubOAuthTokenSecretId:
    Type: String
    Description: The AWS Secrets Manager Secret Id that stores Github OAuth token.
    Default: github/pat
  GitHubOwner:
    Type: String
    Description: The GitHub owner of the repository.
    Default: stax-labs
  BuildSpecFilePath:
    Type: String
    Description: CodeBuild build spec file name for build stage.
    Default: "buildspec-pipeline.yaml"
Resources:
  CD:
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:646794253159:applications/aws-sam-codepipeline-cd
        SemanticVersion: 1.1.0 #version of the ci application
      Parameters:
        GitHubOAuthToken: !Sub '{{resolve:secretsmanager:${GitHubOAuthTokenSecretId}}}'
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: serverless-honeycomb-publisher
        BuildSpecFilePath: !Ref BuildSpecFilePath
        PublishToSAR: "true"
